name: Test Decode Image

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r main/requirements.txt
        pip install opencv-python
        sudo apt-get install -y libzbar0
    - name: Test Decode Qr Image
      run: |
        cd test && python -m unittest test


  build_image_and_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build Front Project
        run: |
          cd front-projetct
          npm install
          npm run build --if-present
          cp index.html ../main/index.html
          cp -R static ../main/
      - name: Build the Docker image and push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: salamandermh/pyqrcode
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
